name: Staging tests for chrome

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * 1-5'  # every day at 10:30 am PT


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Create .env file
        run: |
          touch .env

      - name: Install dependencies
        run: npm install

      - name: Execute tests
        run: npm test

      - name: Archive the test results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-report
          path: TestResults/
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn` 